version: "3"

services:
  db:
    image: postgres:15
    ports:
      - 5400:5432
    environment:
      POSTGRES_DB: frog
      POSTGRES_USER: frog
      POSTGRES_PASSWORD: frog!123
    volumes:
      - ./../resources/database/init.sql:/docker-entrypoint-initdb.d/init.sql